# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.nonTransitiveRClass=true

# Non-secret runtime configuration.
FIREBASE_FUNCTIONS_REGION=us-central1
GOOGLE_WEB_CLIENT_ID=94800580164-u75aqf8ipphgheim855qsv84lvtpmhgl.apps.googleusercontent.com
